### ISSUE TITLE
你好，目前我想要复现代码结果。遇到了一些数据集格式问题

### ISSUE THREAD

**Issue by lqjsurpass** [xuqiantong/RepNet#2]
前期做了一些工作，  但是目前卡在了triplet_generator.py 如何生成训练集，
1.想知道生成的训练集格式是怎样的？
2. 数据层的输入source: " /train_class.txt"中txt文件中label具体标注格式是什么？
3. 能把各网络中用到的txt文件发一份吗？
（source: "/home/xqt/exp/train_class.txt"、train_color.txt、test_class.txt、test_color.txt
三重损失网络中的T_train_class.txt 、T_train_color.txt、T_train_weight.txt 、T_test_class.txt 、T_test_color.txt、 T_test_weight.txt、T-f_train_color.txt 、T-f_train_class.txt）

其实是想知道这些文件的具体格式， 非常感谢！

**Comment by xuqiantong** [comment]
这些文件都比较大，我简单给你讲一下吧。T_train_class.txt，T_train_color.txt，T_train_weight.txt这三个是triplet网络的训练数据，在model中分了三个blob，每个blob就是caffe中最简单的图片+label的形式。第一个txt是triplet的anchor和车型的label，第二个txt是triplet的positive和颜色的label，第二个txt是triplet的negative和weight（后来不用这个weight了）。具体的格式很简单，每行一个图片一个label，中间空格隔开。

**Comment by lqjsurpass** [comment]
论文里和网络中都指出anchor image用于属性分类，学习车型和颜色，但是第一个txt是triplet的anchor和车型的label,怎么指导学习颜色分类，还有negative和weight，这个weight是什么？

非常感谢， 回复这么及时

**Comment by lqjsurpass** [comment]
我开始理解的weight是negative的对应id，前两个txt按您说的分别triplet的anchor和车型的label，positive和颜色的label，但是准确率为0，triplet loss=nan,所以想问下这几个txt的正确格式

**Comment by xuqiantong** [comment]
这三个文件里的内容就是我刚才说的，具体是怎么把label用来学习的，你可以把网络结构可视化一下就很清楚了。weight最开始的设想是每个triplet有不同的权重（在loss里面求和的时候），现在所有triplet都是最难的那种了，也就不需要区分权重了。这个weights在code里面没有被用到。

**Comment by lqjsurpass** [comment]
好的  再次感谢！

**Comment by nana1205** [comment]
请问楼上复现出作者的代码了吗？本人最近也在复现，遇到的问题也是跟楼上一样，可否能有机会跟楼上探讨一下这个项目，不胜感激！！！
